// Automaticaly generated by rust_swig
package net.akaame.myapplication;
import android.support.annotation.NonNull;

public final class Session {

    public Session()  {

        mNativeObj = init();
    }
    private static native long init() ;

    public final int add_and1(int a0)  {

        return do_add_and1(mNativeObj, a0);
    }
    private static native int do_add_and1(long me, int a0) ;

    public static native String greet(@NonNull String a0) ;

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ long mNativeObj;
}