[package]
name = "debug-util"
version = "0.1.0"
authors = ["Evgeniy A. Dushistov <dushistov@mail.ru>"]
edition = "2021"

[dependencies]
env_logger = { version = "0.11.3", default-features = false }
flapigen = { path = "../macroslib" }