@@expect {"file":"c_BasicBox.h","kind":"file"}
// Automatically generated by flapigen

#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
extern "C" {
#endif


    typedef struct BasicBoxOpaque BasicBoxOpaque;
    extern const uintptr_t RustForeignClassBasicBoxElemSize;

    BasicBoxOpaque *BasicBox_new(int32_t value);

    int32_t BasicBox_value(const BasicBoxOpaque * const self);

    void BasicBox_delete(const BasicBoxOpaque *self);

#ifdef __cplusplus
}
#endif


@@end

@@expect {"file":"BasicBox.hpp","kind":"file"}
// Automatically generated by flapigen
#pragma once

//for assert
#include <cassert>
//for std::abort
#include <cstdlib>
//for std::move
#include <utility>
//for std::conditional
#include <type_traits>

#include <stdint.h>

#include "c_BasicBox.h"

namespace org_examples {

template<bool>
class BasicBoxWrapper;
using BasicBox = BasicBoxWrapper<true>;
using BasicBoxRef = BasicBoxWrapper<false>;

template<bool>
struct BasicBoxWrapperCopyControl {};
template<>
struct BasicBoxWrapperCopyControl<true> {
    BasicBoxWrapperCopyControl() = default;
    BasicBoxWrapperCopyControl(const BasicBoxWrapperCopyControl&) = delete;
    BasicBoxWrapperCopyControl& operator=(const BasicBoxWrapperCopyControl&) = delete;
};

template<bool OWN_DATA>
class BasicBoxWrapper : private BasicBoxWrapperCopyControl<OWN_DATA> {
public:
    using value_type = BasicBoxWrapper<true>;
    using ref_type = BasicBoxWrapper<false>;
    friend class BasicBoxWrapper<true>;
    friend class BasicBoxWrapper<false>;

    using SelfType = typename std::conditional<OWN_DATA, BasicBoxOpaque *, const BasicBoxOpaque *>::type;
    using CForeignType = BasicBoxOpaque;

    BasicBoxWrapper(BasicBoxWrapper &&o) noexcept: self_(o.self_)
    {
        o.self_ = nullptr;
    }
    BasicBoxWrapper &operator=(BasicBoxWrapper &&o) noexcept
    {
        assert(this != &o);
        free_mem(this->self_);
        self_ = o.self_;
        o.self_ = nullptr;
        return *this;
    }
    explicit BasicBoxWrapper(SelfType o) noexcept: self_(o) {}
    template<bool B = OWN_DATA, typename std::enable_if<!B, int>::type = 0>
    BasicBoxWrapper(const BasicBoxWrapper<true> &o) noexcept: self_(o.self_) {}
    BasicBoxOpaque *release() noexcept
    {
        BasicBoxOpaque *ret = self_;
        self_ = nullptr;
        return ret;
    }
    explicit operator SelfType() const noexcept { return self_; }

    BasicBoxWrapper(const BasicBoxWrapper&) = default;
    BasicBoxWrapper &operator=(const BasicBoxWrapper&) = default;
    static constexpr const uintptr_t &rust_elem_size = RustForeignClassBasicBoxElemSize;

    BasicBoxWrapper(int32_t value) noexcept
    {

        this->self_ = BasicBox_new(value);
        if (this->self_ == nullptr) {
            std::abort();
        }
    }

    int32_t value() const noexcept;

private:
   static void free_mem(SelfType &p) noexcept
   {
        if (OWN_DATA && p != nullptr) {
            BasicBox_delete(p);
        }
        p = nullptr;
   }
public:
    ~BasicBoxWrapper() noexcept
    {
        free_mem(this->self_);
    }

private:
    SelfType self_;
};
template<bool OWN_DATA>
constexpr const uintptr_t &BasicBoxWrapper<OWN_DATA>::rust_elem_size;


    template<bool OWN_DATA>
    inline int32_t BasicBoxWrapper<OWN_DATA>::value() const noexcept
    {

        int32_t ret = BasicBox_value(this->self_);
        return ret;
    }

} // namespace org_examples

@@end

@@expect {"file":"c_BasicRc.h","kind":"file"}
// Automatically generated by flapigen

#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
extern "C" {
#endif


    typedef struct BasicRcOpaque BasicRcOpaque;
    extern const uintptr_t RustForeignClassBasicRcElemSize;

    BasicRcOpaque *BasicRc_new(int32_t value);

    int32_t BasicRc_value(const BasicRcOpaque * const self);

    void BasicRc_delete(const BasicRcOpaque *self);

#ifdef __cplusplus
}
#endif


@@end

@@expect {"file":"BasicRc.hpp","kind":"file"}
// Automatically generated by flapigen
#pragma once

//for assert
#include <cassert>
//for std::abort
#include <cstdlib>
//for std::move
#include <utility>
//for std::conditional
#include <type_traits>

#include <stdint.h>

#include "c_BasicRc.h"

namespace org_examples {

template<bool>
class BasicRcWrapper;
using BasicRc = BasicRcWrapper<true>;
using BasicRcRef = BasicRcWrapper<false>;

template<bool>
struct BasicRcWrapperCopyControl {};
template<>
struct BasicRcWrapperCopyControl<true> {
    BasicRcWrapperCopyControl() = default;
    BasicRcWrapperCopyControl(const BasicRcWrapperCopyControl&) = delete;
    BasicRcWrapperCopyControl& operator=(const BasicRcWrapperCopyControl&) = delete;
};

template<bool OWN_DATA>
class BasicRcWrapper : private BasicRcWrapperCopyControl<OWN_DATA> {
public:
    using value_type = BasicRcWrapper<true>;
    using ref_type = BasicRcWrapper<false>;
    friend class BasicRcWrapper<true>;
    friend class BasicRcWrapper<false>;

    using SelfType = typename std::conditional<OWN_DATA, BasicRcOpaque *, const BasicRcOpaque *>::type;
    using CForeignType = BasicRcOpaque;

    BasicRcWrapper(BasicRcWrapper &&o) noexcept: self_(o.self_)
    {
        o.self_ = nullptr;
    }
    BasicRcWrapper &operator=(BasicRcWrapper &&o) noexcept
    {
        assert(this != &o);
        free_mem(this->self_);
        self_ = o.self_;
        o.self_ = nullptr;
        return *this;
    }
    explicit BasicRcWrapper(SelfType o) noexcept: self_(o) {}
    template<bool B = OWN_DATA, typename std::enable_if<!B, int>::type = 0>
    BasicRcWrapper(const BasicRcWrapper<true> &o) noexcept: self_(o.self_) {}
    BasicRcOpaque *release() noexcept
    {
        BasicRcOpaque *ret = self_;
        self_ = nullptr;
        return ret;
    }
    explicit operator SelfType() const noexcept { return self_; }

    BasicRcWrapper(const BasicRcWrapper&) = default;
    BasicRcWrapper &operator=(const BasicRcWrapper&) = default;
    static constexpr const uintptr_t &rust_elem_size = RustForeignClassBasicRcElemSize;

    BasicRcWrapper(int32_t value) noexcept
    {

        this->self_ = BasicRc_new(value);
        if (this->self_ == nullptr) {
            std::abort();
        }
    }

    int32_t value() const noexcept;

private:
   static void free_mem(SelfType &p) noexcept
   {
        if (OWN_DATA && p != nullptr) {
            BasicRc_delete(p);
        }
        p = nullptr;
   }
public:
    ~BasicRcWrapper() noexcept
    {
        free_mem(this->self_);
    }

private:
    SelfType self_;
};
template<bool OWN_DATA>
constexpr const uintptr_t &BasicRcWrapper<OWN_DATA>::rust_elem_size;


    template<bool OWN_DATA>
    inline int32_t BasicRcWrapper<OWN_DATA>::value() const noexcept
    {

        int32_t ret = BasicRc_value(this->self_);
        return ret;
    }

} // namespace org_examples

@@end

@@expect {"file":"c_BasicArc.h","kind":"file"}
// Automatically generated by flapigen

#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
extern "C" {
#endif


    typedef struct BasicArcOpaque BasicArcOpaque;
    extern const uintptr_t RustForeignClassBasicArcElemSize;

    BasicArcOpaque *BasicArc_new(int32_t value);

    int32_t BasicArc_value(const BasicArcOpaque * const self);

    void BasicArc_delete(const BasicArcOpaque *self);

#ifdef __cplusplus
}
#endif


@@end

@@expect {"file":"BasicArc.hpp","kind":"file"}
// Automatically generated by flapigen
#pragma once

//for assert
#include <cassert>
//for std::abort
#include <cstdlib>
//for std::move
#include <utility>
//for std::conditional
#include <type_traits>

#include <stdint.h>

#include "c_BasicArc.h"

namespace org_examples {

template<bool>
class BasicArcWrapper;
using BasicArc = BasicArcWrapper<true>;
using BasicArcRef = BasicArcWrapper<false>;

template<bool>
struct BasicArcWrapperCopyControl {};
template<>
struct BasicArcWrapperCopyControl<true> {
    BasicArcWrapperCopyControl() = default;
    BasicArcWrapperCopyControl(const BasicArcWrapperCopyControl&) = delete;
    BasicArcWrapperCopyControl& operator=(const BasicArcWrapperCopyControl&) = delete;
};

template<bool OWN_DATA>
class BasicArcWrapper : private BasicArcWrapperCopyControl<OWN_DATA> {
public:
    using value_type = BasicArcWrapper<true>;
    using ref_type = BasicArcWrapper<false>;
    friend class BasicArcWrapper<true>;
    friend class BasicArcWrapper<false>;

    using SelfType = typename std::conditional<OWN_DATA, BasicArcOpaque *, const BasicArcOpaque *>::type;
    using CForeignType = BasicArcOpaque;

    BasicArcWrapper(BasicArcWrapper &&o) noexcept: self_(o.self_)
    {
        o.self_ = nullptr;
    }
    BasicArcWrapper &operator=(BasicArcWrapper &&o) noexcept
    {
        assert(this != &o);
        free_mem(this->self_);
        self_ = o.self_;
        o.self_ = nullptr;
        return *this;
    }
    explicit BasicArcWrapper(SelfType o) noexcept: self_(o) {}
    template<bool B = OWN_DATA, typename std::enable_if<!B, int>::type = 0>
    BasicArcWrapper(const BasicArcWrapper<true> &o) noexcept: self_(o.self_) {}
    BasicArcOpaque *release() noexcept
    {
        BasicArcOpaque *ret = self_;
        self_ = nullptr;
        return ret;
    }
    explicit operator SelfType() const noexcept { return self_; }

    BasicArcWrapper(const BasicArcWrapper&) = default;
    BasicArcWrapper &operator=(const BasicArcWrapper&) = default;
    static constexpr const uintptr_t &rust_elem_size = RustForeignClassBasicArcElemSize;

    BasicArcWrapper(int32_t value) noexcept
    {

        this->self_ = BasicArc_new(value);
        if (this->self_ == nullptr) {
            std::abort();
        }
    }

    int32_t value() const noexcept;

private:
   static void free_mem(SelfType &p) noexcept
   {
        if (OWN_DATA && p != nullptr) {
            BasicArc_delete(p);
        }
        p = nullptr;
   }
public:
    ~BasicArcWrapper() noexcept
    {
        free_mem(this->self_);
    }

private:
    SelfType self_;
};
template<bool OWN_DATA>
constexpr const uintptr_t &BasicArcWrapper<OWN_DATA>::rust_elem_size;


    template<bool OWN_DATA>
    inline int32_t BasicArcWrapper<OWN_DATA>::value() const noexcept
    {

        int32_t ret = BasicArc_value(this->self_);
        return ret;
    }

} // namespace org_examples

@@end
