@@expect {"file":"BasicBox.java","kind":"file"}
// Automatically generated by flapigen
package org.example;


public final class BasicBox {

    public BasicBox(int value) {
        mNativeObj = init(value);
    }
    private static native long init(int value);

    public final int value() {
        int ret = do_value(mNativeObj);

        return ret;
    }
    private static native int do_value(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ BasicBox(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}
@@end

@@expect {"file":"BasicRc.java","kind":"file"}
// Automatically generated by flapigen
package org.example;


public final class BasicRc {

    public BasicRc(int value) {
        mNativeObj = init(value);
    }
    private static native long init(int value);

    public final int value() {
        int ret = do_value(mNativeObj);

        return ret;
    }
    private static native int do_value(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ BasicRc(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}
@@end

@@expect {"file":"BasicArc.java","kind":"file"}
// Automatically generated by flapigen
package org.example;


public final class BasicArc {

    public BasicArc(int value) {
        mNativeObj = init(value);
    }
    private static native long init(int value);

    public final int value() {
        int ret = do_value(mNativeObj);

        return ret;
    }
    private static native int do_value(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ BasicArc(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}
@@end
