@@expect {"after":"\n","before":"// Automatically generated by flapigen\n","file":"SomeObserver.java","greedy_match":true,"kind":"between"}
package org.example;


public interface SomeObserver {


    void onStateChanged1(int a0, boolean a1);


    boolean onStateChanged2(boolean a0, double a1);

}
@@end
