@@expect {"file":"LocalCallback.hpp","kind":"file"}
// Automatically generated by flapigen
#pragma once

#include <cassert>
#include <memory> //for std::unique_ptr


#include "c_LocalCallback.h"

namespace org_examples {

class LocalCallback {
public:
    virtual ~LocalCallback() noexcept {}

    virtual void onEvent() const noexcept = 0;


    static C_LocalCallback to_c_interface(std::unique_ptr<LocalCallback> p) noexcept
    {
        assert(p != nullptr);
        C_LocalCallback ret;
        ret.opaque = p.release();

        ret.C_LocalCallback_deref = c_LocalCallback_deref;
        ret.onEvent = c_onEvent;

        return ret;
    }
    static C_LocalCallback reference_to_c_interface(LocalCallback &cpp_interface) noexcept
    {
        C_LocalCallback ret;
        ret.opaque = &cpp_interface;
        ret.onEvent = c_onEvent;

        ret.C_LocalCallback_deref = [](void *) {};
        return ret;
    }
    static C_LocalCallback reference_to_c_interface(const LocalCallback &cpp_interface) noexcept
    {
        C_LocalCallback ret;
        ret.opaque = const_cast<void *>(static_cast<const void *>(&cpp_interface));
        ret.onEvent = c_onEvent;

        ret.C_LocalCallback_deref = [](void *) {};
        return ret;
    }
protected:

    static void c_LocalCallback_deref(void *opaque)
    {
        auto p = static_cast<LocalCallback *>(opaque);
        delete p;
    }

    static void c_onEvent(void *opaque)
    {
        assert(opaque != nullptr);
        auto pi = static_cast<const LocalCallback *>(opaque);

        pi->onEvent();
    }

};
} // namespace org_examples

@@end
