@@expect {"after":" noexcept;\n\n","before":"            std::abort();\n        }\n    }\n\n    ","file":"A.hpp","kind":"between"}
static void a(BRef b)
@@end

@@expect {"after":" noexcept;\n\n","before":"            std::abort();\n        }\n    }\n\n    ","file":"B.hpp","kind":"between"}
static void b(ARef a)
@@end

@@expect {"file":"A.hpp","kind":"between","after":"namespace org_examples {"}
// Automatically generated by flapigen
#pragma once

//for assert
#include <cassert>
//for std::abort
#include <cstdlib>
//for std::move
#include <utility>
//for std::conditional
#include <type_traits>

#include "B_fwd.hpp"
#include "c_B.h"

#include "c_A.h"


@@end

@@expect {"file":"B.hpp","kind":"between","after":"namespace org_examples {"}
// Automatically generated by flapigen
#pragma once

//for assert
#include <cassert>
//for std::abort
#include <cstdlib>
//for std::move
#include <utility>
//for std::conditional
#include <type_traits>

#include "A_fwd.hpp"
#include "c_A.h"

#include "c_B.h"


@@end

@@expect {"file":"c_A.h","kind":"file"}
// Automatically generated by flapigen

#pragma once

//for (u)intX_t types
#include <stdint.h>
typedef struct BOpaque BOpaque;

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
extern "C" {
#endif


    typedef struct AOpaque AOpaque;
    extern const uintptr_t RustForeignClassAElemSize;

    AOpaque *A_default();

    void A_a(const BOpaque * b);

    void A_delete(const AOpaque *self);

#ifdef __cplusplus
}
#endif


@@end

@@expect {"file":"c_B.h","kind":"file"}
// Automatically generated by flapigen

#pragma once

//for (u)intX_t types
#include <stdint.h>
typedef struct AOpaque AOpaque;

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
extern "C" {
#endif


    typedef struct BOpaque BOpaque;
    extern const uintptr_t RustForeignClassBElemSize;

    BOpaque *B_default();

    void B_b(const AOpaque * a);

    void B_delete(const BOpaque *self);

#ifdef __cplusplus
}
#endif


@@end
