@@expect {"after":"\npublic:\n   ","before":"// Automatically generated by flapigen\n","file":"Foo.hpp","kind":"between"}
#pragma once

//for assert
#include <cassert>
//for std::abort
#include <cstdlib>
//for std::move
#include <utility>
//for std::conditional
#include <type_traits>

#include "Boo.hpp"
#include "c_Boo.h"
#include "rust_option.h"
#include <optional>
#include <stdint.h>
#include "ControlItem.hpp"
#include "rust_str.h"
#include <string_view>

#include "c_Foo.h"

namespace org_examples {

template<bool>
class FooWrapper;
using Foo = FooWrapper<true>;
using FooRef = FooWrapper<false>;

template<bool>
struct FooWrapperCopyControl {};
template<>
struct FooWrapperCopyControl<true> {
    FooWrapperCopyControl() = default;
    FooWrapperCopyControl(const FooWrapperCopyControl&) = delete;
    FooWrapperCopyControl& operator=(const FooWrapperCopyControl&) = delete;
};

template<bool OWN_DATA>
class FooWrapper : private FooWrapperCopyControl<OWN_DATA> {
@@end

@@expect {"after":" const noexcept;\n\n    st","before":"std::abort();\n        }\n    }\n\n    ","file":"Foo.hpp","kind":"between"}
std::optional<Boo> f1()
@@end

@@expect {"after":" const noexcept;\n\n    std::optional<uint","before":"std::optional<Boo> f1() const noexcept;\n\n    ","file":"Foo.hpp","kind":"between"}
std::optional<double> f2()
@@end

@@expect {"after":" const noexcept;\n\n    std::optional<uint","before":"std::optional<double> f2() const noexcept;\n\n    ","file":"Foo.hpp","kind":"between"}
std::optional<uint32_t> f3()
@@end

@@expect {"after":" const noexcept;\n\n    std::optional<BooR","before":"std::optional<uint32_t> f3() const noexcept;\n\n    ","file":"Foo.hpp","kind":"between"}
std::optional<uintptr_t> f4()
@@end

@@expect {"after":" const noexcept;\n\n    std::optional<Cont","before":"std::optional<uintptr_t> f4() const noexcept;\n\n    ","file":"Foo.hpp","kind":"between"}
std::optional<BooRef> f5()
@@end

@@expect {"after":"\n\n    std::optional<uint64_t> f7() const","before":"std::optional<BooRef> f5() const noexcept;\n\n    ","file":"Foo.hpp","kind":"between"}
std::optional<ControlItem> f6() const noexcept;
@@end

@@expect {"after":" const noexcept;\n\n    std::optional<std:","before":"std::optional<ControlItem> f6() const noexcept;\n\n    ","file":"Foo.hpp","kind":"between"}
std::optional<uint64_t> f7()
@@end

@@expect {"after":" const noexcept;\n\n    std::optional<Rust","before":"std::optional<uint64_t> f7() const noexcept;\n\n    ","file":"Foo.hpp","kind":"between"}
std::optional<std::string_view> f8()
@@end

@@expect {"after":"\n\n    template<bool OWN_","before":"return (ret.is_some != 0) ? std::optional<uint64_t>(ret.val.data) : std::optional<uint64_t>();\n    }\n\n    ","file":"Foo.hpp","kind":"between"}
template<bool OWN_DATA>
    inline std::optional<std::string_view> FooWrapper<OWN_DATA>::f8() const noexcept
    {

        struct CRustOptionCRustStrView ret = Foo_f8(this->self_);
        return (ret.is_some != 0) ? std::optional<std::string_view>(std::string_view{ ret.val.data.data, ret.val.data.len }) : std::optional<std::string_view>();
    }
@@end

@@expect {"after":" const noexcept;\n\n    std::optional<bool","before":"std::optional<std::string_view> f8() const noexcept;\n\n    ","file":"Foo.hpp","kind":"between"}
std::optional<RustString> f9()
@@end

@@expect {"after":" const noexcept;\n\nprivate:\n   static voi","before":"std::optional<RustString> f9() const noexcept;\n\n    ","file":"Foo.hpp","kind":"between"}
std::optional<bool> f10()
@@end

@@expect {"after":"\n\n    template<bool OWN_","before":"return (ret.is_some != 0) ? std::optional<BooRef>(BooRef{ static_cast<const BooOpaque *>(ret.val.data) }) : std::optional<BooRef>();\n    }\n\n    ","file":"Foo.hpp","kind":"between"}
template<bool OWN_DATA>
    inline std::optional<ControlItem> FooWrapper<OWN_DATA>::f6() const noexcept
    {

        struct CRustOptionu32 ret = Foo_f6(this->self_);
        return (ret.is_some != 0) ? std::optional<ControlItem>(static_cast<ControlItem>(ret.val.data)) : std::optional<ControlItem>();
    }
@@end

@@expect {"after":"\n\n    struct CRustOptionu64 Foo_f7(const","before":"struct CRustOption4232const3232c_void Foo_f5(const FooOpaque * const self);\n\n    ","file":"c_Foo.h","kind":"between"}
struct CRustOptionu32 Foo_f6(const FooOpaque * const self);
@@end
