@@expect {"file":"c_XDirect.h","kind":"file"}
// Automatically generated by flapigen

#pragma once

//for (u)intX_t types
#include <stdint.h>
typedef struct YOpaque YOpaque;

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
extern "C" {
#endif


    typedef struct XDirectOpaque XDirectOpaque;
    extern const uintptr_t RustForeignClassXDirectElemSize;

    XDirectOpaque *XDirect_default();

    void XDirect_take_y(YOpaque * y);

    YOpaque * XDirect_get_y(const XDirectOpaque * const self);

    void XDirect_delete(const XDirectOpaque *self);

#ifdef __cplusplus
}
#endif


@@end

@@expect {"file":"c_XOptional.h","kind":"file"}
// Automatically generated by flapigen

#pragma once

//for (u)intX_t types
#include <stdint.h>
struct CRustOption4232mut3232c_void;

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
extern "C" {
#endif


    typedef struct XOptionalOpaque XOptionalOpaque;
    extern const uintptr_t RustForeignClassXOptionalElemSize;

    XOptionalOpaque *XOptional_default();

    void XOptional_take_y(struct CRustOption4232mut3232c_void y);

    struct CRustOption4232mut3232c_void XOptional_get_y(const XOptionalOpaque * const self);

    void XOptional_delete(const XOptionalOpaque *self);

#ifdef __cplusplus
}
#endif


@@end

@@expect {"file":"c_XVec.h","kind":"file"}
// Automatically generated by flapigen

#pragma once

//for (u)intX_t types
#include <stdint.h>
struct CRustForeignVecY;

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
extern "C" {
#endif


    typedef struct XVecOpaque XVecOpaque;
    extern const uintptr_t RustForeignClassXVecElemSize;

    XVecOpaque *XVec_default();

    void XVec_take_y(struct CRustForeignVecY y);

    struct CRustForeignVecY XVec_get_y(const XVecOpaque * const self);

    void XVec_delete(const XVecOpaque *self);

#ifdef __cplusplus
}
#endif


@@end

@@expect {"file":"c_XSlice.h","kind":"file"}
// Automatically generated by flapigen

#pragma once

//for (u)intX_t types
#include <stdint.h>
struct CRustSliceForeignY;

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
extern "C" {
#endif


    typedef struct XSliceOpaque XSliceOpaque;
    extern const uintptr_t RustForeignClassXSliceElemSize;

    XSliceOpaque *XSlice_default();

    void XSlice_take_y(struct CRustSliceForeignY y);

    struct CRustSliceForeignY XSlice_get_y(const XSliceOpaque * const self);

    void XSlice_delete(const XSliceOpaque *self);

#ifdef __cplusplus
}
#endif


@@end

@@expect {"file":"XDirect.hpp","kind":"between","after":"namespace org_examples {"}
// Automatically generated by flapigen
#pragma once

//for assert
#include <cassert>
//for std::abort
#include <cstdlib>
//for std::move
#include <utility>
//for std::conditional
#include <type_traits>

#include "Y.hpp"
#include "c_Y.h"

#include "c_XDirect.h"


@@end

@@expect {"file":"XOptional.hpp","kind":"between","after":"namespace org_examples {"}
// Automatically generated by flapigen
#pragma once

//for assert
#include <cassert>
//for std::abort
#include <cstdlib>
//for std::move
#include <utility>
//for std::conditional
#include <type_traits>

#include "Y.hpp"
#include "c_Y.h"
#include "rust_option.h"
#include <optional>

#include "c_XOptional.h"


@@end

@@expect {"file":"XVec.hpp","kind":"between","after":"namespace org_examples {"}
// Automatically generated by flapigen
#pragma once

//for assert
#include <cassert>
//for std::abort
#include <cstdlib>
//for std::move
#include <utility>
//for std::conditional
#include <type_traits>

#include "Y.hpp"
#include "c_Y.h"
#include "RustForeignVecY.h"

#include "c_XVec.h"


@@end

@@expect {"file":"XSlice.hpp","kind":"between","after":"namespace org_examples {"}
// Automatically generated by flapigen
#pragma once

//for assert
#include <cassert>
//for std::abort
#include <cstdlib>
//for std::move
#include <utility>
//for std::conditional
#include <type_traits>

#include "Y.hpp"
#include "c_Y.h"
#include "CRustSliceForeignY.h"

#include "c_XSlice.h"


@@end
