@@expect {"after":"template<bool OWN_DATA>\nconstexpr const ","before":"// Automatically generated by flapigen\n","file":"BtAddr.hpp","kind":"between"}
#pragma once

//for assert
#include <cassert>
//for std::abort
#include <cstdlib>
//for std::move
#include <utility>
//for std::conditional
#include <type_traits>

#include <QString>
#include "rust_str.h"

#include "c_BtAddr.h"

namespace org_examples {

template<bool>
class BtAddrWrapper;
using BtAddr = BtAddrWrapper<true>;
using BtAddrRef = BtAddrWrapper<false>;


template<bool OWN_DATA>
class BtAddrWrapper {
public:
    using value_type = BtAddrWrapper<true>;
    using ref_type = BtAddrWrapper<false>;
    friend class BtAddrWrapper<true>;
    friend class BtAddrWrapper<false>;

    using SelfType = typename std::conditional<OWN_DATA, BtAddrOpaque *, const BtAddrOpaque *>::type;
    using CForeignType = BtAddrOpaque;

    BtAddrWrapper(BtAddrWrapper &&o) noexcept: self_(o.self_)
    {
        o.self_ = nullptr;
    }
    BtAddrWrapper &operator=(BtAddrWrapper &&o) noexcept
    {
        assert(this != &o);
        free_mem(this->self_);
        self_ = o.self_;
        o.self_ = nullptr;
        return *this;
    }
    explicit BtAddrWrapper(SelfType o) noexcept: self_(o) {}
    template<bool B = OWN_DATA, typename std::enable_if<!B, int>::type = 0>
    BtAddrWrapper(const BtAddrWrapper<true> &o) noexcept: self_(o.self_) {}
    BtAddrOpaque *release() noexcept
    {
        BtAddrOpaque *ret = self_;
        self_ = nullptr;
        return ret;
    }
    explicit operator SelfType() const noexcept { return self_; }

    BtAddrWrapper(const BtAddrWrapper& o) noexcept {
         if (o.self_ != nullptr) {
             if (OWN_DATA) {
                 self_ = BtAddr_clone(o.self_);
             } else {
                 self_ = o.self_;
             }
         } else {
             self_ = nullptr;
         }
    }
    BtAddrWrapper &operator=(const BtAddrWrapper& o) noexcept {
        if (this != &o) {
            free_mem(this->self_);
            if (o.self_ != nullptr) {
                if (OWN_DATA) {
                    self_ = BtAddr_clone(o.self_);
                } else {
                    self_ = o.self_;
                }
            } else {
                self_ = nullptr;
            }
        }
        return *this;
    }
    static constexpr const uintptr_t &rust_elem_size = RustForeignClassBtAddrElemSize;
private:

    BtAddrWrapper() noexcept {}
public:

    QString to_string() const noexcept;

    BtAddr clone() const noexcept;

private:
   static void free_mem(SelfType &p) noexcept
   {
        if (OWN_DATA && p != nullptr) {
            BtAddr_delete(p);
        }
        p = nullptr;
   }
public:
    ~BtAddrWrapper() noexcept
    {
        free_mem(this->self_);
    }

private:
    SelfType self_;
};

@@end
