@@expect {"file":"PlainA.hpp","kind":"between","after":"namespace org_examples {"}
// Automatically generated by flapigen
#pragma once

//for assert
#include <cassert>
//for std::abort
#include <cstdlib>
//for std::move
#include <utility>

#include "PlainB_fwd.hpp"
#include "c_PlainB.h"

#include "c_PlainA.h"


@@end

@@expect {"file":"PlainB.hpp","kind":"between","after":"namespace org_examples {"}
// Automatically generated by flapigen
#pragma once

//for assert
#include <cassert>
//for std::abort
#include <cstdlib>
//for std::move
#include <utility>

#include "PlainA_fwd.hpp"
#include "c_PlainA.h"

#include "c_PlainB.h"


@@end
