@@expect {"file":"c_SelfInclude.h","kind":"file"}
// Automatically generated by flapigen
#pragma once

#include <stdint.h>
#include "header_probe.h"

struct C_SelfInclude {
    void *opaque;
    //! call by Rust side when callback not need anymore
    void (*C_SelfInclude_deref)(void *opaque);

    void (*onProbe)(struct CHeaderProbe value, void *opaque);

};

@@end
