@@expect {"file":"DefaultOwned.java","kind":"file"}
// Automatically generated by flapigen
package org.example;


public final class DefaultOwned {

    public DefaultOwned() {
        mNativeObj = init();
    }
    private static native long init();

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ DefaultOwned(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}
@@end
