@@expect {"file":"c_DefaultOwned.h","kind":"file"}
// Automatically generated by flapigen

#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
extern "C" {
#endif


    typedef struct DefaultOwnedOpaque DefaultOwnedOpaque;
    extern const uintptr_t RustForeignClassDefaultOwnedElemSize;

    DefaultOwnedOpaque *DefaultOwned_default();

    void DefaultOwned_delete(const DefaultOwnedOpaque *self);

#ifdef __cplusplus
}
#endif


@@end
