@@expect {"file":"SliceHost.hpp","kind":"item","name":"SliceHostWrapper<OWN_DATA>::nodes","form":"definition"}
template<bool OWN_DATA>
    inline RustSlice<const BoxNode> SliceHostWrapper<OWN_DATA>::nodes() const noexcept
    {

        struct CRustSliceForeignBoxNode ret = SliceHost_nodes(this->self_);
        return RustSlice<const BoxNode>{ret};
    }
@@end

@@expect {"file":"SliceHost.hpp","kind":"item","name":"SliceHostWrapper<OWN_DATA>::nodes_mut","form":"definition"}
template<bool OWN_DATA>
    inline RustSlice<BoxNode> SliceHostWrapper<OWN_DATA>::nodes_mut() noexcept
    {

        struct CRustSliceMutForeignBoxNode ret = SliceHost_nodes_mut(this->self_);
        return RustSlice<BoxNode>{ret};
    }
@@end

@@expect {"file":"SliceHost.hpp","kind":"item","name":"SliceHostWrapper<OWN_DATA>::sum_nodes","form":"definition"}
template<bool OWN_DATA>
    inline int32_t SliceHostWrapper<OWN_DATA>::sum_nodes(RustSlice<const BoxNode> values) noexcept
    {

        int32_t ret = SliceHost_sum_nodes(values.as_c<CRustSliceForeignBoxNode>());
        return ret;
    }
@@end

@@expect {"file":"SliceHost.hpp","kind":"item","name":"SliceHostWrapper<OWN_DATA>::update_nodes","form":"definition"}
template<bool OWN_DATA>
    inline void SliceHostWrapper<OWN_DATA>::update_nodes(RustSlice<BoxNode> values) noexcept
    {

        SliceHost_update_nodes(values.as_c<CRustSliceMutForeignBoxNode>());
    }
@@end

@@expect {"file":"CRustSliceForeignBoxNode.h","kind":"file"}
// Automatically generated by flapigen
#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
#endif
            #include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
struct CRustSliceForeignBoxNode {
    const struct BoxNodeOpaque * data;
    uintptr_t len;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
#include "rust_slice_tmpl.hpp"
#include "BoxNode_fwd.hpp"
#endif

@@end

@@expect {"file":"CRustSliceMutForeignBoxNode.h","kind":"file"}
// Automatically generated by flapigen
#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
#endif
            #include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
struct CRustSliceMutForeignBoxNode {
    struct BoxNodeOpaque * data;
    uintptr_t len;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
#include "rust_slice_tmpl.hpp"
#include "BoxNode_fwd.hpp"
#endif

@@end
