@@expect {"after":"\n    uintptr_t len;\n    uintptr_t capacity;\n};\n\n#ifdef __cplusplus\n} // extern \"","before":"static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,\n   \"our conversion usize <-> uintptr_t is wrong\");\n#endif\n\n#ifdef __cplusplus\nextern \"C\" {\n#endif\n","file":"RustForeignVecFoo.h","kind":"between"}
struct CRustForeignVecFooElem {
    uint8_t _unused;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustForeignVecFoo {
    CRustForeignVecFooElem * data;
@@end

@@expect {"file":"RustForeignVecBoo.h","kind":"file"}
// Automatically generated by flapigen
#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustForeignVecBooElem {
    uint8_t _unused;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustForeignVecBoo {
    CRustForeignVecBooElem * data;
    uintptr_t len;
    uintptr_t capacity;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustForeignVecBoo RustForeignVecBoo_new();
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
void RustForeignVecBoo_free(struct CRustForeignVecBoo v);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
void RustForeignVecBoo_push(CRustForeignVecBoo * v, void * e);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
void * RustForeignVecBoo_remove(CRustForeignVecBoo * v, uintptr_t idx);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus

#include "Boo_fwd.hpp"
#include "rust_vec_impl.hpp"

namespace org_examples {
using RustForeignVecBoo = RustVec<CRustForeignVecBoo, internal::ForeignVecPolicy<BooRef, CRustForeignVecBoo, RustForeignVecBoo_new, RustForeignVecBoo_free, RustForeignVecBoo_push, RustForeignVecBoo_remove>>;
}
#endif

@@end

@@expect {"after":"\n\n    std::v","before":"            std::abort();\n        }\n    }\n\n    ","file":"Boo.hpp","kind":"between"}
RustForeignVecFoo get_foo_arr() const noexcept;
@@end

@@expect {"after":"\n\n    struct","before":"BooOpaque *Boo_new(int32_t a0, uintptr_t a1);\n\n    ","file":"c_Boo.h","kind":"between"}
struct CRustForeignVecFoo Boo_get_foo_arr(const BooOpaque * const self);
@@end

@@expect {"after":"\n\n    templa","before":"constexpr const uintptr_t &BooWrapper<OWN_DATA>::rust_elem_size;\n\n\n    ","file":"Boo.hpp","kind":"between"}
template<bool OWN_DATA>
    inline RustForeignVecFoo BooWrapper<OWN_DATA>::get_foo_arr() const noexcept
    {

        struct CRustForeignVecFoo ret = Boo_get_foo_arr(this->self_);
        return RustForeignVecFoo{ret};
    }
@@end

@@expect {"after":"\n\n    struct","before":"struct CRustForeignVecFoo Boo_get_foo_arr(const BooOpaque * const self);\n\n    ","file":"c_Boo.h","kind":"between"}
struct CRustResult4232mut3232c_voidCRustString Boo_get_foo_with_err(const BooOpaque * const self);
@@end

@@expect {"after":"\n\n    std::v","before":"RustForeignVecFoo get_foo_arr() const noexcept;\n\n    ","file":"Boo.hpp","kind":"between"}
std::variant<Foo, RustString> get_foo_with_err() const noexcept;
@@end

@@expect {"after":"\n\n    template<bool OWN_","before":"return RustForeignVecFoo{ret};\n    }\n\n    ","file":"Boo.hpp","kind":"between"}
template<bool OWN_DATA>
    inline std::variant<Foo, RustString> BooWrapper<OWN_DATA>::get_foo_with_err() const noexcept
    {

        struct CRustResult4232mut3232c_voidCRustString ret = Boo_get_foo_with_err(this->self_);
        return ret.is_ok != 0 ?
              std::variant<Foo, RustString> { Foo(static_cast<FooOpaque *>(ret.data.ok)) } :
              std::variant<Foo, RustString> { RustString{ret.data.err} };
    }
@@end

@@expect {"after":"\n\n    void Boo_delete(const BooOpaque *s","before":"struct CRustResult4232mut3232c_voidCRustString Boo_get_foo_with_err(const BooOpaque * const self);\n\n    ","file":"c_Boo.h","kind":"between"}
struct CRustResultCRustForeignVecFooCRustString Boo_get_foo_arr_with_err(const BooOpaque * const self);

    struct CRustForeignVecBoo Boo_get_boo_arr(const BooOpaque * const self);
@@end

@@expect {"after":"\n\nprivate:\n   static void free_mem(SelfT","before":"std::variant<Foo, RustString> get_foo_with_err() const noexcept;\n\n    ","file":"Boo.hpp","kind":"between"}
std::variant<RustForeignVecFoo, RustString> get_foo_arr_with_err() const noexcept;

    RustForeignVecBoo get_boo_arr() const noexcept;
@@end

@@expect {"after":"\n\n} // namespace org_exa","before":"std::variant<Foo, RustString> { RustString{ret.data.err} };\n    }\n\n    ","file":"Boo.hpp","kind":"between"}
template<bool OWN_DATA>
    inline std::variant<RustForeignVecFoo, RustString> BooWrapper<OWN_DATA>::get_foo_arr_with_err() const noexcept
    {

        struct CRustResultCRustForeignVecFooCRustString ret = Boo_get_foo_arr_with_err(this->self_);
        return ret.is_ok != 0 ?
              std::variant<RustForeignVecFoo, RustString> { RustForeignVecFoo{ret.data.ok} } :
              std::variant<RustForeignVecFoo, RustString> { RustString{ret.data.err} };
    }

    template<bool OWN_DATA>
    inline RustForeignVecBoo BooWrapper<OWN_DATA>::get_boo_arr() const noexcept
    {

        struct CRustForeignVecBoo ret = Boo_get_boo_arr(this->self_);
        return RustForeignVecBoo{ret};
    }
@@end
