@@expect {"file":"Utils.java","kind":"file"}
// Automatically generated by flapigen
package org.example;

/**
 * This is documentation comment
 */
public final class Utils {
    /**
     * Very important function
     */
    public static native int f(int a0);

    private Utils() {}
}
@@end
