@@expect {"file":"RustVecArcNode.h","kind":"file"}
// Automatically generated by flapigen
#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
#endif
            #include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
struct CRustForeignVecArcNodeElem {
    uint8_t _unused;
};

#ifdef __cplusplus
} // extern "C" {
#endif
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
struct CRustForeignVecArcNode {
    CRustForeignVecArcNodeElem * data;
    uintptr_t len;
    uintptr_t capacity;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustForeignVecArcNode RustForeignVecArcNode_new();
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
void RustForeignVecArcNode_free(struct CRustForeignVecArcNode v);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
void RustForeignVecArcNode_push(CRustForeignVecArcNode * v, void * e);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
void * RustForeignVecArcNode_remove(CRustForeignVecArcNode * v, uintptr_t idx);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
#include "rust_vec_impl.hpp"
#include "CRustSliceForeignIndirectArcNode.h"

namespace org_examples {
using RustVecArcNode = RustVec<CRustForeignVecArcNode, internal::IndirectForeignVecPolicy<RustSlice<const ArcNode, ArcNodeAccess>, ArcNodeAccess, CRustForeignVecArcNode, RustForeignVecArcNode_new, RustForeignVecArcNode_free, RustForeignVecArcNode_push, RustForeignVecArcNode_remove>>;
}
#endif

@@end

@@expect {"file":"RustVecRcNode.h","kind":"file"}
// Automatically generated by flapigen
#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
#endif
            #include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
struct CRustForeignVecRcNodeElem {
    uint8_t _unused;
};

#ifdef __cplusplus
} // extern "C" {
#endif
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
struct CRustForeignVecRcNode {
    CRustForeignVecRcNodeElem * data;
    uintptr_t len;
    uintptr_t capacity;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustForeignVecRcNode RustForeignVecRcNode_new();
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
void RustForeignVecRcNode_free(struct CRustForeignVecRcNode v);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
void RustForeignVecRcNode_push(CRustForeignVecRcNode * v, void * e);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
void * RustForeignVecRcNode_remove(CRustForeignVecRcNode * v, uintptr_t idx);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
#include "rust_vec_impl.hpp"
#include "CRustSliceForeignIndirectRcNode.h"

namespace org_examples {
using RustVecRcNode = RustVec<CRustForeignVecRcNode, internal::IndirectForeignVecPolicy<RustSlice<const RcNode, RcNodeAccess>, RcNodeAccess, CRustForeignVecRcNode, RustForeignVecRcNode_new, RustForeignVecRcNode_free, RustForeignVecRcNode_push, RustForeignVecRcNode_remove>>;
}
#endif

@@end

@@expect {"file":"CRustSliceForeignIndirectArcNode.h","kind":"file"}
// Automatically generated by flapigen
#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
#endif
            #include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
struct CRustSliceForeignIndirectArcNodeElem {
    uint8_t _unused;
};

#ifdef __cplusplus
} // extern "C" {
#endif
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
struct CRustSliceForeignIndirectArcNode {
    const CRustSliceForeignIndirectArcNodeElem * data;
    uintptr_t len;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
const void * CRustSliceForeignIndirectArcNode_get(struct CRustSliceForeignIndirectArcNode slice, uintptr_t idx);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
#include "rust_slice_tmpl.hpp"
#include "ArcNode_fwd.hpp"

namespace org_examples {
template<bool> class ArcNodeWrapper;
struct ArcNodeAccess {
    using storage_type = CRustSliceForeignIndirectArcNodeElem;
    template<typename Ref = ArcNodeWrapper<false>>
    static Ref index(internal::SliceStorage<const storage_type *> slice, size_t idx) noexcept {
        auto p = static_cast<const typename Ref::CForeignType *>(
            CRustSliceForeignIndirectArcNode_get(CRustSliceForeignIndirectArcNode{slice.data, slice.len}, idx));
        return Ref{p};
    }
};
}
#endif

@@end

@@expect {"file":"ArcNode.hpp","kind":"item","name":"ArcNodeWrapper<OWN_DATA>::children","form":"definition"}
template<bool OWN_DATA>
    inline RustVecArcNode ArcNodeWrapper<OWN_DATA>::children() const noexcept
    {

        struct CRustForeignVecArcNode ret = ArcNode_children(this->self_);
        return RustVecArcNode{ret};
    }
@@end

@@expect {"file":"VecHost.hpp","kind":"item","name":"VecHostWrapper<OWN_DATA>::echo_arcs","form":"definition"}
template<bool OWN_DATA>
    inline RustVecArcNode VecHostWrapper<OWN_DATA>::echo_arcs(RustVecArcNode values) noexcept
    {

        struct CRustForeignVecArcNode ret = VecHost_echo_arcs(values.release());
        return RustVecArcNode{ret};
    }
@@end

@@expect {"file":"VecHost.hpp","kind":"item","name":"VecHostWrapper<OWN_DATA>::echo_rcs","form":"definition"}
template<bool OWN_DATA>
    inline RustVecRcNode VecHostWrapper<OWN_DATA>::echo_rcs(RustVecRcNode values) noexcept
    {

        struct CRustForeignVecRcNode ret = VecHost_echo_rcs(values.release());
        return RustVecRcNode{ret};
    }
@@end
