@@expect {"file":"ArcNode.hpp","kind":"item","name":"ArcNodeWrapper<OWN_DATA>::children","form":"definition"}
template<bool OWN_DATA>
    inline RustSlice<const ArcNode, ArcNodeAccess> ArcNodeWrapper<OWN_DATA>::children() const noexcept
    {

        struct CRustSliceForeignIndirectArcNode ret = ArcNode_children(this->self_);
        return RustSlice<const ArcNode, ArcNodeAccess>{ret};
    }
@@end

@@expect {"file":"IndirectSliceHost.hpp","kind":"item","name":"IndirectSliceHostWrapper<OWN_DATA>::arcs","form":"definition"}
template<bool OWN_DATA>
    inline RustSlice<const ArcNode, ArcNodeAccess> IndirectSliceHostWrapper<OWN_DATA>::arcs() const noexcept
    {

        struct CRustSliceForeignIndirectArcNode ret = IndirectSliceHost_arcs(this->self_);
        return RustSlice<const ArcNode, ArcNodeAccess>{ret};
    }
@@end

@@expect {"file":"IndirectSliceHost.hpp","kind":"item","name":"IndirectSliceHostWrapper<OWN_DATA>::rcs","form":"definition"}
template<bool OWN_DATA>
    inline RustSlice<const RcNode, RcNodeAccess> IndirectSliceHostWrapper<OWN_DATA>::rcs() const noexcept
    {

        struct CRustSliceForeignIndirectRcNode ret = IndirectSliceHost_rcs(this->self_);
        return RustSlice<const RcNode, RcNodeAccess>{ret};
    }
@@end

@@expect {"file":"IndirectSliceHost.hpp","kind":"item","name":"IndirectSliceHostWrapper<OWN_DATA>::other_arcs","form":"definition"}
template<bool OWN_DATA>
    inline RustSlice<const OtherArcNode, OtherArcNodeAccess> IndirectSliceHostWrapper<OWN_DATA>::other_arcs() const noexcept
    {

        struct CRustSliceForeignIndirectOtherArcNode ret = IndirectSliceHost_other_arcs(this->self_);
        return RustSlice<const OtherArcNode, OtherArcNodeAccess>{ret};
    }
@@end

@@expect {"file":"IndirectSliceHost.hpp","kind":"item","name":"IndirectSliceHostWrapper<OWN_DATA>::take_arcs","form":"definition"}
template<bool OWN_DATA>
    inline uintptr_t IndirectSliceHostWrapper<OWN_DATA>::take_arcs(RustSlice<const ArcNode, ArcNodeAccess> values) noexcept
    {

        uintptr_t ret = IndirectSliceHost_take_arcs(values.as_c<CRustSliceForeignIndirectArcNode>());
        return ret;
    }
@@end

@@expect {"file":"IndirectSliceHost.hpp","kind":"item","name":"IndirectSliceHostWrapper<OWN_DATA>::take_rcs","form":"definition"}
template<bool OWN_DATA>
    inline uintptr_t IndirectSliceHostWrapper<OWN_DATA>::take_rcs(RustSlice<const RcNode, RcNodeAccess> values) noexcept
    {

        uintptr_t ret = IndirectSliceHost_take_rcs(values.as_c<CRustSliceForeignIndirectRcNode>());
        return ret;
    }
@@end

@@expect {"file":"CRustSliceForeignIndirectArcNode.h","kind":"file"}
// Automatically generated by flapigen
#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustSliceForeignIndirectArcNodeElem {
    uint8_t _unused;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustSliceForeignIndirectArcNode {
    const CRustSliceForeignIndirectArcNodeElem * data;
    uintptr_t len;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
const void * CRustSliceForeignIndirectArcNode_get(struct CRustSliceForeignIndirectArcNode slice, uintptr_t idx);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
#include "rust_slice_tmpl.hpp"
#include "ArcNode_fwd.hpp"

namespace org_examples {
template<bool> class ArcNodeWrapper;
struct ArcNodeAccess {
    using storage_type = CRustSliceForeignIndirectArcNodeElem;
    template<typename Ref = ArcNodeWrapper<false>>
    static Ref index(internal::SliceStorage<const storage_type *> slice, size_t idx) noexcept {
        auto p = static_cast<const typename Ref::CForeignType *>(
            CRustSliceForeignIndirectArcNode_get(CRustSliceForeignIndirectArcNode{slice.data, slice.len}, idx));
        return Ref{p};
    }
};
}
#endif

@@end

@@expect {"file":"CRustSliceForeignIndirectRcNode.h","kind":"file"}
// Automatically generated by flapigen
#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustSliceForeignIndirectRcNodeElem {
    uint8_t _unused;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustSliceForeignIndirectRcNode {
    const CRustSliceForeignIndirectRcNodeElem * data;
    uintptr_t len;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
const void * CRustSliceForeignIndirectRcNode_get(struct CRustSliceForeignIndirectRcNode slice, uintptr_t idx);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
#include "rust_slice_tmpl.hpp"
#include "RcNode_fwd.hpp"

namespace org_examples {
template<bool> class RcNodeWrapper;
struct RcNodeAccess {
    using storage_type = CRustSliceForeignIndirectRcNodeElem;
    template<typename Ref = RcNodeWrapper<false>>
    static Ref index(internal::SliceStorage<const storage_type *> slice, size_t idx) noexcept {
        auto p = static_cast<const typename Ref::CForeignType *>(
            CRustSliceForeignIndirectRcNode_get(CRustSliceForeignIndirectRcNode{slice.data, slice.len}, idx));
        return Ref{p};
    }
};
}
#endif

@@end

@@expect {"file":"CRustSliceForeignIndirectOtherArcNode.h","kind":"file"}
// Automatically generated by flapigen
#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustSliceForeignIndirectOtherArcNodeElem {
    uint8_t _unused;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustSliceForeignIndirectOtherArcNode {
    const CRustSliceForeignIndirectOtherArcNodeElem * data;
    uintptr_t len;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
const void * CRustSliceForeignIndirectOtherArcNode_get(struct CRustSliceForeignIndirectOtherArcNode slice, uintptr_t idx);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
#include "rust_slice_tmpl.hpp"
#include "OtherArcNode_fwd.hpp"

namespace org_examples {
template<bool> class OtherArcNodeWrapper;
struct OtherArcNodeAccess {
    using storage_type = CRustSliceForeignIndirectOtherArcNodeElem;
    template<typename Ref = OtherArcNodeWrapper<false>>
    static Ref index(internal::SliceStorage<const storage_type *> slice, size_t idx) noexcept {
        auto p = static_cast<const typename Ref::CForeignType *>(
            CRustSliceForeignIndirectOtherArcNode_get(CRustSliceForeignIndirectOtherArcNode{slice.data, slice.len}, idx));
        return Ref{p};
    }
};
}
#endif

@@end
