@@expect {"file":"RustVecVecRowFoo.h","kind":"file"}
// Automatically generated by flapigen
#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustVecVecRowFooElem {
    uint8_t _unused;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustVecVecRowFooRowElem {
    uint8_t _unused;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustVecVecRowFooRowSlice {
    const CRustVecVecRowFooRowElem * data;
    uintptr_t len;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustVecVecRowFoo {
    CRustVecVecRowFooElem * data;
    uintptr_t len;
    uintptr_t capacity;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustVecVecRowFoo RustVecVecRowFoo_new();
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
void RustVecVecRowFoo_free(struct CRustVecVecRowFoo v);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustVecVecRowFooRowSlice RustVecVecRowFoo_get(struct CRustVecVecRowFoo v, uintptr_t idx);
#ifdef __cplusplus
} // extern "C" {
#endif
#include "RustForeignVecRowFoo.h"

#ifdef __cplusplus
extern "C" {
#endif
void RustVecVecRowFoo_push(CRustVecVecRowFoo * v, struct CRustForeignVecRowFoo row);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustForeignVecRowFoo RustVecVecRowFoo_remove(CRustVecVecRowFoo * v, uintptr_t idx);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
#include "rust_vec_impl.hpp"
#include "RustForeignVecRowFoo.h"
#include "CRustSliceVecForeignRowFoo.h"

namespace org_examples {
using RustVecVecRowFoo = RustVec<CRustVecVecRowFoo, internal::NestedForeignVecPolicy<
    RustForeignVecRowFoo, RustSlice<const RowFoo>,
    RustSliceVecForeignRowFoo,
    CRustVecVecRowFoo, CRustForeignVecRowFoo, CRustVecVecRowFooRowSlice,
    RustVecVecRowFoo_new, RustVecVecRowFoo_free, RustVecVecRowFoo_get, RustVecVecRowFoo_push, RustVecVecRowFoo_remove>>;
}
#endif

@@end

@@expect {"file":"RustVecVecRowBar.h","kind":"file"}
// Automatically generated by flapigen
#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustVecVecRowBarElem {
    uint8_t _unused;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustVecVecRowBarRowElem {
    uint8_t _unused;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustVecVecRowBarRowSlice {
    const CRustVecVecRowBarRowElem * data;
    uintptr_t len;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustVecVecRowBar {
    CRustVecVecRowBarElem * data;
    uintptr_t len;
    uintptr_t capacity;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustVecVecRowBar RustVecVecRowBar_new();
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
void RustVecVecRowBar_free(struct CRustVecVecRowBar v);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustVecVecRowBarRowSlice RustVecVecRowBar_get(struct CRustVecVecRowBar v, uintptr_t idx);
#ifdef __cplusplus
} // extern "C" {
#endif
#include "RustForeignVecRowBar.h"

#ifdef __cplusplus
extern "C" {
#endif
void RustVecVecRowBar_push(CRustVecVecRowBar * v, struct CRustForeignVecRowBar row);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustForeignVecRowBar RustVecVecRowBar_remove(CRustVecVecRowBar * v, uintptr_t idx);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
#include "rust_vec_impl.hpp"
#include "RustForeignVecRowBar.h"
#include "CRustSliceVecForeignRowBar.h"

namespace org_examples {
using RustVecVecRowBar = RustVec<CRustVecVecRowBar, internal::NestedForeignVecPolicy<
    RustForeignVecRowBar, RustSlice<const RowBar>,
    RustSliceVecForeignRowBar,
    CRustVecVecRowBar, CRustForeignVecRowBar, CRustVecVecRowBarRowSlice,
    RustVecVecRowBar_new, RustVecVecRowBar_free, RustVecVecRowBar_get, RustVecVecRowBar_push, RustVecVecRowBar_remove>>;
}
#endif

@@end

@@expect {"file":"NestedVecHost.hpp","kind":"item","name":"NestedVecHostWrapper<OWN_DATA>::echo_foos","form":"definition"}
template<bool OWN_DATA>
    inline RustVecVecRowFoo NestedVecHostWrapper<OWN_DATA>::echo_foos(RustVecVecRowFoo rows) noexcept
    {

        struct CRustVecVecRowFoo ret = NestedVecHost_echo_foos(rows.release());
        return RustVecVecRowFoo{ret};
    }
@@end

@@expect {"file":"CRustSliceVecForeignRowFoo.h","kind":"file"}
// Automatically generated by flapigen
#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustSliceVecForeignRowFooElem {
    uint8_t _unused;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustSliceVecForeignRowFooRowElem {
    uint8_t _unused;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustSliceVecForeignRowFooRowSlice {
    const CRustSliceVecForeignRowFooRowElem * data;
    uintptr_t len;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustSliceVecForeignRowFoo {
    const CRustSliceVecForeignRowFooElem * data;
    uintptr_t len;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustSliceVecForeignRowFooRowSlice CRustSliceVecForeignRowFoo_get(struct CRustSliceVecForeignRowFoo slice, uintptr_t index);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
#include "rust_vec_impl.hpp"
#include "RustForeignVecRowFoo.h"

namespace org_examples {
using RustSliceVecForeignRowFoo = RustSlice<const RustForeignVecRowFoo,
    internal::NestedForeignVecSliceAccess<
        RustSlice<const RowFoo>,
        CRustSliceVecForeignRowFoo, CRustSliceVecForeignRowFooElem, CRustSliceVecForeignRowFooRowSlice, CRustSliceVecForeignRowFoo_get>>;
}
#endif

@@end

@@expect {"file":"NestedVecHost.hpp","kind":"item","name":"NestedVecHostWrapper<OWN_DATA>::count_foos","form":"definition"}
template<bool OWN_DATA>
    inline uintptr_t NestedVecHostWrapper<OWN_DATA>::count_foos(RustSliceVecForeignRowFoo rows) noexcept
    {

        uintptr_t ret = NestedVecHost_count_foos(rows.as_c<CRustSliceVecForeignRowFoo>());
        return ret;
    }
@@end
