@@expect {"after":"\n","before":"static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,\n   \"our conversion usize <-> uintptr_t is wrong\");\n#endif\n\n","file":"c_fn_i324232mut3232c_void_t.h","kind":"between"}
typedef void (*c_fn_i324232mut3232c_void_t)(int32_t, void *);
@@end

@@expect {"after":"\n\n#ifdef __c","before":"extern \"C\" {\n#endif\n","file":"CFnOncei32.h","kind":"between"}
struct CFnOncei32 {
    c_fn_i324232mut3232c_void_t cb;
    void * ctx;
};
@@end

@@expect {"after":"\n\n    static","before":"friend class TestFutureWrapper<false>;\n\n    ","file":"TestFuture.hpp","kind":"between"}
static std::future<int32_t> call_fn() noexcept;
@@end

@@expect {"after":"\n\n    templa","before":"static std::future<std::variant<int32_t, RustString>> call_fn2() noexcept;\n\n};\n\n\n    ","file":"TestFuture.hpp","kind":"between"}
template<bool OWN_DATA>
    inline std::future<int32_t> TestFutureWrapper<OWN_DATA>::call_fn() noexcept
    {

        auto tmp = new std::promise<int32_t>;
        auto f = tmp->get_future();
        struct CFnOncei32 a0;
        a0.ctx = tmp;
        a0.cb = [](int32_t arg, void *opaque) {
            auto arg_cpp = arg;
            auto promise = static_cast<std::promise<int32_t> *>(opaque);
            promise->set_value(std::move(arg_cpp));
            delete promise;
        };

        TestFuture_call_fn(std::move(a0));
        return f;

    }
@@end

@@expect {"file":"c_fn_CRustResulti32CRustString4232mut3232c_void_t.h","kind":"file"}
// Automatically generated by flapigen
#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
#endif
#include "rust_resulti32CRustString.h"

typedef void (*c_fn_CRustResulti32CRustString4232mut3232c_void_t)(CRustResulti32CRustString, void *);

@@end

@@expect {"after":"\n\n};\n\n\n    t","before":"static std::future<int32_t> call_fn() noexcept;\n\n    ","file":"TestFuture.hpp","kind":"between"}
static std::future<std::variant<int32_t, RustString>> call_fn2() noexcept;
@@end

@@expect {"after":"\n\n} // names","before":"\n    }\n\n    ","file":"TestFuture.hpp","kind":"between"}
template<bool OWN_DATA>
    inline std::future<std::variant<int32_t, RustString>> TestFutureWrapper<OWN_DATA>::call_fn2() noexcept
    {

        auto tmp = new std::promise<std::variant<int32_t, RustString>>;
        auto f = tmp->get_future();
        struct CFnOnceCRustResulti32CRustString a0;
        a0.ctx = tmp;
        a0.cb = [](CRustResulti32CRustString arg, void *opaque) {
            auto arg_cpp = arg.is_ok != 0 ?
              std::variant<int32_t, RustString> { arg.data.ok } :
              std::variant<int32_t, RustString> { RustString{arg.data.err} };
            auto promise = static_cast<std::promise<std::variant<int32_t, RustString>> *>(opaque);
            promise->set_value(std::move(arg_cpp));
            delete promise;
        };

        TestFuture_call_fn2(std::move(a0));
        return f;

    }
@@end
