@@expect {"file":"rust_vec_string.h","kind":"file"}
// Automatically generated by flapigen
#pragma once

//for (u)intX_t types
#include <stdint.h>

#ifdef __cplusplus
static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
   "our conversion usize <-> uintptr_t is wrong");
#endif

typedef struct CRustVecStringElem CRustVecStringElem;
typedef struct CRustVecString CRustVecString;

#ifdef __cplusplus
extern "C" {
#endif
struct CRustVecStringElem {
    uint8_t _unused;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustVecString {
    CRustVecStringElem * data;
    uintptr_t len;
    uintptr_t capacity;
};

#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustVecString crust_vec_string_new();
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
void crust_vec_string_free(struct CRustVecString value);
#ifdef __cplusplus
} // extern "C" {
#endif
#include "rust_str.h"

#ifdef __cplusplus
extern "C" {
#endif
struct CRustStrView crust_vec_string_get(struct CRustVecString value, uintptr_t index);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
void crust_vec_string_push(CRustVecString * value, struct CRustString item);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
extern "C" {
#endif
struct CRustString crust_vec_string_remove(CRustVecString * value, uintptr_t index);
#ifdef __cplusplus
} // extern "C" {
#endif

#ifdef __cplusplus
#include "rust_vec_impl.hpp"
#include "rust_string_slice.h"

namespace org_examples {
namespace internal {
template <typename View> struct StringVecPolicy {
    using value_type = RustString;
    using reference = View;
    using iterator = SliceIterator<CRustVecString, StringVecPolicy<View>>;
    using const_iterator = iterator;
    using SliceAccess = StringSliceAccess<View, CRustSliceString, CRustSliceStringElem,
                                          crust_slice_string_get>;
    using Slice = RustSlice<const View, SliceAccess>;

    static CRustVecString empty() noexcept { return crust_vec_string_new(); }
    static void free(CRustVecString vec) noexcept { crust_vec_string_free(vec); }
    static Slice as_slice(CRustVecString vec) noexcept
    {
        return Slice{ static_cast<const CRustSliceStringElem *>(
                          static_cast<const void *>(vec.data)), vec.len };
    }
    static View index(CRustVecString vec, size_t i) noexcept
    {
        const auto str = crust_vec_string_get(vec, i);
        return str.len == 0 ? View{} : View{ str.data, str.len };
    }
    static iterator begin(CRustVecString vec) noexcept { return iterator{ vec, 0 }; }
    static const_iterator cbegin(CRustVecString vec) noexcept { return begin(vec); }
    static iterator end(CRustVecString vec) noexcept { return iterator{ vec, vec.len }; }
    static const_iterator cend(CRustVecString vec) noexcept { return end(vec); }
    static void push(CRustVecString &vec, RustString value) noexcept
    {
        crust_vec_string_push(&vec, value.release());
    }
    static RustString remove(CRustVecString &vec, size_t i) noexcept
    {
        assert(i < vec.len);
        return RustString{ crust_vec_string_remove(&vec, i) };
    }
};
} // namespace internal
} // namespace org_examples
#endif

#ifdef __cplusplus
namespace org_examples {
using RustVecString = RustVec<CRustVecString, internal::StringVecPolicy<std::string_view>>;
}
#endif

@@end

@@expect {"file":"StringVecs.hpp","kind":"item","name":"strings","form":"declaration"}
RustVecString strings() const noexcept;
@@end

@@expect {"file":"StringVecs.hpp","kind":"item","name":"append","form":"declaration"}
RustVecString append(RustVecString values) const noexcept;
@@end

@@expect {"file":"StringVecs.hpp","kind":"item","name":"StringVecsWrapper<OWN_DATA>::append","form":"definition"}
template<bool OWN_DATA>
    inline RustVecString StringVecsWrapper<OWN_DATA>::append(RustVecString values) const noexcept
    {

        struct CRustVecString ret = StringVecs_append(this->self_, values.release());
        return RustVecString{ret};
    }
@@end
